---
title: "Self-efficacy definitions"
author: "Nicolás Tobar"
---

## Learning process depends on Mindset

Learning theories tend to be concerned with the acquisition of knowledge (Cognitive issues) or execution of response patterns (Behavioral issues) to study performance on an activity. With SCT the discipline started to consider also how Self-referents mechanisms affect the acquisition of competence in a determined task.

As motivation and affect elements contain the Self-reactiveness dimension of agency self-regulation, Self-reflectiveness is principally explained by the individual's self-efficacy level. As a part of the intention of human agency, this concept supposes forethought in its structure. In that sense, *Self-efficacy is not a self-perception of the ability to execute an action but an orchestration or continued improvisation of multiple skills to manage the ever-changing situation around mastering an activity. Perceived self-efficacy is concerned by judgments of how well one can execute courses of action required to deal with prospective situations* [@bandura_selfefficacy_1982].

This concept was so important for Bandura because it occupies a pivotal role in the causal structure of development on Social Cognitive Theory as states that beliefs affect adaptation and change not only in their own right but through their impact on other determinants. i) Efficacy plays a central role in the self-regulation of motivation through goal challenges and outcome expectations. ii) Efficacy determines the challenge to undertake, how much effort to expend in the endeavor, how long to persevere in the face of obstacles and failure, and whether failures are motivating or demoralizing. iii) Efficacy beliefs also play a key role in shaping the courses lives take by influencing the types of activities and environments people choose to get into. In synthesis, efficacy shapes the mindset and the environment, crucial for reinforcing the mastery of the activity to which one is dedicated [@bandura_selfefficacy_1995; @steele_stereotype_1995].

Debating human genetic-environmental determination, Bandura’s Self-efficacy concept states that learning or development exceeds inner capabilities. If one judges oneself as capable of managing new competencies, one can undertake them with better probabilities of achievement. In technical terms, self-efficacy is an internal mediator of the covariation between external or environmental factors and behavior or actions. Also, it is proved that self-efficacy could shape neuron network growth, so it’s a determinant for material-internal conditions of learning.

## Lines of information

Self-efficacy is based on four lines of information individuals perceive:

1.  *Master experience*. Success builds robust beliefs on self-efficacy. Failure undermines it, especially if it occurs before a sense of self-efficacy is firmly established. Inverse with quick results, which easily discourage if a failure appears.

2.  *Vicarious experience*. Seeing people like oneself succeed through perseverant effort raises the observer’s belief that one, too, can master comparable activity. The inverse token occurs when observing similar people's failures.

3.  *Social persuasion*. Convince verbally that you don’t have the capabilities to master some given activities. Discouragement to mobilize effort and sustain it by instilling self-doubts about personal deficiencies resulting from other people's influences.

4.  *Psychological and emotional states*. Stress reaction and tension are signs of vulnerability and poor performance.

These sources of information are not inherently instructive for the individual. The result depends on their cognitive processing of them [@bandura_selfefficacy_1995]. This may vary according to the psychological uniqueness of each person. Four mind mechanisms for processing this information:

1.  *Cognitive processing*. Shape types of scenarios constructed and rehearse them. Visualizing failure or achieving goals of courses of action imagined.

2.  *Motivational processing*. There are three elements that are used to understand how motivation is shaped. The first focuses on satisfaction with one performance based on personal attributes (Causal attributions/ Attribution theory). The second focuses on benefits or attainments achieved in the activity (Outcome expectancy/ Expectancy value theory). The third is based on a sense of personal progress in mastering the path (Recognized goals/ Goal theory).

3.  *Affective process*. Efficacy affects potential threats and situations that are fraught with dangers. It can modify people's sense of control. As more control is perceived, there is less anxiety about threats and coping with problematic situations.

4.  *Selection process*. Efficacy depends on the types of activities and environment people choose to stay. This decision-making process also shapes the environment to increase/decrease Self-efficacy. As low self-efficacy, low aspiration to take difficult tasks, and less aspiration to take difficult tasks and present resilence coping them.

## Types of Self-efficacy

Self-efficacy is a multidimensional concept that can be explored by different approaches. To propose thematic research around this concept, it’s necessary to distinguish between different types or perspectives.

Individual self-efficacy level differ on three distinct but interrelated judgements: Magnitude, Strength, and Generalizability[^03_selfeff_def-1].

[^03_selfeff_def-1]: This Self-efficacy judgments were proposed by @brief_self_1981 years ago but then recovered by @compeau_computer_1995 to study computer Self-efficacy, so I think it’s important to include them.

The *Magnitude* of self-efficacy refers to the level of task difficulty one believes is attainable. Individuals with a high self-efficacy magnitude might be expected to perceive themselves as able to accomplish more difficult computing tasks than those with lower self-efficacy judgments. Alternatively, self-efficacy magnitude might be gauged regarding support levels required to undertake a task.

Self-efficacy *Strength* refers to the level of conviction about personal judgment. It also reflects the resistance of self-efficacy to apparently disconfirming information. Individuals with a weak sense of self-efficacy will be frustrated more easily by obstacles to their performance and will respond by lowering their perceptions of their capability. By contrast, individuals with a strong sense of efficacy will not be deterred by difficult problems, will retain their sense of self-efficacy, and as a result of their continued persistence, are more likely to overcome whatever obstacle is present.

Self-efficacy *Generalizability* reflects the degree to which the judgment is limited to a particular domain of activity or not. For example, these domains might be considered to reflect different hardware and software configurations within a computing context. Thus, individuals with high computer self-efficacy generalizability would expect to be able to competently use different software packages and different computer systems, while those with low computer self-efficacy generalizability would perceive their capabilities as limited to particular software packages or computer systems.

Generally, Self-efficacy has two ways to be studied: As perceived capabilities for *task achievement* and as a *self-regulatory attitude*. *Task self-efficacy* involves the beliefs that one can or cannot perform a single instance of a circumscribed behavior at different levels of performance. *Self-regulatory self-efficacy* is the confidence in how *one can (or could)* achieve tasks in the context of potential barriers. Studies focusing on capabilities usually emphasize the *magnitude* of the task, i.e., its degree of difficulty or complexity, and the linear achievement of the masterization process. By contrast, studies focused on attitudinal aspects give greater importance to *strength* to keep self-efficacy levels in difficult contexts. The first approach questions the capability to reach higher and higher levels in the activity domain, and the second focuses on persistance or resistance in the face of adversities presented by an activity [@williams_confounded_2016]. Saying in a different way, @schwarzer_socialcognitive_2000 distinguish between *action self-efficacy* as confidence that the subject can (or could) perform the behavior even when it requires setting goals and planning, and *coping self-efficacy* as confidence that the subject can (or could) perform the behavior even in the face of initial setbacks or lack of social support.

Some contributions to this debate suggest five types to classify self-efficacy constructs. What varies across these conceptualizations of self-efficacy is whether the perceived capability to perform the target behavior is to be judged in isolation (i.e., *task self-efficacy*) or under various conditions, such as in the context of potential barriers (i.e., *self-regulatory efficacy*), when initiating a new behavior (i.e., *initiation self-efficacy*), following relapse (i.e., *recovery self-efficacy*), or in the face of potentially stressful life events (i.e., *coping self-efficacy*) [@marlatt_selfefficacy_1995].

## Several others

After these theoretical definitions, it’s important to note the empirical performance of the Self-efficacy variable. Bandura provides a lot of information that could be useful for our studies. First note. Self-efficacy doesn’t have a positive linear direction with performance. An individual with higher levels of self-efficacy could present lower levels of task achievement. The same with lower grades of self-efficacy. This is because performance and learning, as Social Cognitive Theory tries to defend, is a situated process, and this depends on context, personal attributes, or the specific nature of the task the individual imagines mastering. Self-efficacy covariation with competencies is tied to gender, age, the social groups around the environments, and so on [@bandura_selfefficacy_1995]. [^03_selfeff_def-2]

[^03_selfeff_def-2]: This insight support our first ICILS study, where we try to approach the under/overestimation phenomenon on digital Self-efficacy. Also, open possibilities to understand why Self-efficacy empirical studies tends to divide constructs on basic and specialized tasks; probably present different effects because of the nature of this concept.

Second note. Self-efficacy is not only an important predictor of an individual's competences, but also of the decisions he or she makes in life. In the formation period, the perception of boys' and girls' capabilities defines the careers they pursue or their interests and affiliative preferences. A person's life path depends on competences, interests, and affiliative preferences, all of which are influenced by self-efficacy, especially on educational experience [@bandura_selfefficacy_1995].

Third note. Incentives are also important for explaining self-efficacy. In Social Cognitive Theory, interests grow from satisfactions derived from fulfilling internal standards and from perceiving self-efficacy obtained from performance accomplishments and other sources of efficacy information. By making self-satisfaction conditional on a certain level of performance mastery, people create self-incentives for their efforts [@bandura_selfefficacy_1995].

Fourth note. The resonance theory raised by @rosa_resonancia_2019 is one of the principal theoretical contributions for sociology. The claim of Rosa is to re-found a sociological approximation that move from the resources and competence question to concern the last and principal problem for social sciences: The relations with the world and good life. In this sense, he takes up Bandura's effort to think of psychotherapy in positive terms (not as a way of avoiding the pathological), and transfers it to sociology, especially to actual critical theory. Bandura's self-efficacy is a conceptual pillar of this proposal. In his book observes that the current research on self-efficacy use this concept to explain the expansion of resources and opportunities on individuals (Competences and achievements), but the same Bandura demonstrated that levels of intrinsic motivation with an activity doesn't grow up with the raise of outcomes, but with the sense that world that the world becomes attainable and speaks to you through your own actions. If resonance theory is taken seriously, the decisive factor in understanding the variation in self-efficacy is not the results perceptions, but the interaction-process of the activity. Then, the increase or reach of individuals' life chances should not be approximated by opportunities per-se, abstract if one will, but by opportunities to establish vibrant threads and meaningful relationships with the activity being evaluated.

## References {.unnumbered}
