---
title: "Constructing Self-efficacy measurements"
author: "Nicolás Tobar"
---

## Bandura's Insights

At the late stage of his large Self-efficacy research agenda, @banduraGuideConstructingSelfefficacy2006 wrote a standard guide for constructing self-efficacy scales. In this text he takes over some critiques and suggestions around the years and tries to propose a definitive method for operationalize self-efficacy. In this section their most relevants comments are selected and exposed.

First Recommendation: Bandura claim that in human life people cannot mastery every realm of life. Self-efficacy differ by the given pursuits in the area in which it its developed. Thus, the efficacy belief system is not a global trait but a differentiated set of self-beliefs linked to distinct realms of functioning. Multidomain measures are necessary because it reveals the patterning and degree of generality of people’s sense of personal efficacy. *There is no all-purpose measure of perceived self-efficacy. Scales of perceived self-efficacy must be tailored to the particular domain of functioning that is the object of interest.*

Second recommendation: Efficacy items should accurately reflect the construct. Self-efficacy is concerned with perceived capability. *The items should be phrased in terms of can do rather than will do. Can is a judgment of capability; will is a statement of intention.*

Third recommendation: Perceived self-efficacy should also be distinguished from other constructs such as self-esteem, locus of control, and outcome expectancies. *Perceived efficacy is a judgment of capability; self-esteem is a judgment of self-worth; locus of control is about outcome responsibility (one’s actions or external forces); and outcome expectancies are judgments on the results of the action, not about capabilities to do the action.*

Fourth recommendation: A comprehensive self-efficacy assessment would be linked to the behavioral factors that influence people to exercise some control. Behavior is better predicted by people’s beliefs in their capabilities to do whatever is needed to succeed than by their beliefs in only one aspect of self-efficacy relevant to the domain. Thus, multifaceted efficacy scales not only have predictive utility but provide insights into the dynamics of self-management of behavior. If self-efficacy scales are targeted to factors that, in fact, have little or no impact on the domain of functioning, such research cannot yield a predictive relation. *In short, self-efficacy scales must be tailored to activity domains and assess the multifaceted ways in which efficacy beliefs operate within the selected activity domain. The efficacy scales must be linked to factors that, in fact, determine quality of functioning in the domain of interest.*

Fifth recommendation: *Perceived efficacy should be measured against task demands that represent gradations of challenges or impediments to successful performance.* Self-efficacy appraisals reflect the level of difficulty individuals believe they can surmount. If there are no obstacles to overcome, the activity is easily performable, and everyone is highly efficacious. The events over which personal influence is exercised can vary widely. It  may entail regulating one’s own motivation, thought processes, performance level, emotional states, or altering environmental conditions. The nature of the challenges against which personal efficacy is judged will vary depending on the sphere of activity. Constructing scales to assess self-regulatory efficacy requires preliminary work to identify the forms the challenges and impediments take.

Sixth recommendation: *The record of the strength of efficacy beliefs have to be on a 100-point scale, ranging in 10-unit intervals from 0 (“Cannot do”); through intermediate degrees of assurance, 50 (“Moderately certain can do”); to complete assurance, 100 (“Highly certain can do”).* Scales that use only a few steps should be avoided because they are less sensitive and less reliable. People usually avoid the extreme positions so a scale with only a few steps may, in actual use, shrink to one or two points. Including too few steps loses differentiating information because people who use the same response category may differ if intermediate steps were included.

Seventh recommendation: *Efficacy scales are unipolar, ranging from 0 to a maximum strength. They do not include negative numbers because a judgment of complete incapability (0) has no lower gradations.* Bipolar scales with negative gradations below the zero point that one cannot perform a given level of activity do not make sense [@pajaresResponseFormatWriting2001].

Eigth recommendation: *People are asked to judge their operative capabilities as of now, not their potential capabilities or their expected future capabilities.* It is easy for people to imagine themselves to be fully efficacious in some hypothetical future.

## Critiques of Bandura and others' proposals

In 1984, Cognitive Therapy and Research dedicated a special issue to Bandura's thesis on self-efficacy. Some relevant scholars commented on Bandura's theory's limitations and confusing issues.

An article by @eastmanTheoreticalMethodologicalDifficulties1984 on that issue said that Bandura's definition of self-efficacy is fundamentally ambiguous regarding the distinction between self-efficacy expectations and outcome expectations. Separating acts (tasks) from outcomes, particularly in complex activities, is difficult in real-life experiences. Many behaviors involve a continuous interplay between actions and their outcomes, making it challenging to assess self-efficacy independently of outcome considerations. The authors express skepticism about the applicability of Bandura's findings to everyday life, arguing that most psychological issues involve tasks and outcomes that are not clearly defined. They believe this complexity makes it difficult for individuals to assess their self-efficacy accurately.

This condition is traduced in empirical problems. The empirical studies conducted by Bandura often assess self-efficacy through tasks that are discrete and limited in scope, which may not adequately capture the broader complexities of real-life situations where multiple outcomes exist. The assessments of self-efficacy in Bandura's studies do not account for the variability and unpredictability of outcomes that individuals might consider, thus failing to demonstrate that efficacy judgments can be made independently of outcome considerations [@marzillierContinuingProblemsSelfefficacy1984]. [^04_construct_scales-1]

[^04_construct_scales-1]: I add this to the agenda review because I think could be useful for General and Specialized Digital Self-efficacy distinction. If one follow the argument, in General tasks there are more possibilities to discriminate between efficacy expectatives and outcome than on Specialized tasks.

Recent contributions have indicated that the self-efficacy definition's grey area with outcome expectations also affects its relation with motivational mechanisms of action. If individuals do not analytically distinguish, with utmost clarity, efficacy expectations from expected outcomes in action, it is likely that the degree of agency is mostly explained by the motivations that generate the outcomes rather than by perceived singular capabilities. In that sense, Self-efficacy would be an epiphenomenon of motivation rather than a determinant. However, if self-efficacy and motivation are intermingled, there would be confusion in distinguishing the agency's self-reactiveness and self-reflectiveness moments that Bandura previously suggested [@williamsConfoundedSelfEfficacyConstruct2016].

As a result, Researchers on Self-efficacy indicate that the operationalization of the concept needs to avoid assessments that confound the judgments of efficacy and motivation of the action. To rate the confidence in a target behavior, some assessments ask participants whether they *would do* the action or *how confident* they are to achieve it. This would be a better strategy than *'can-do'* scale construction strategies. @kirschSelfefficacyOutcomeExpectancies1995 explains there are two colloquial uses of the phrase can do. One meaning reflects perceived capability per se based on one's estimation of their actual capability to perform a task (i.e. the original definition of efficacy expectancy as distinct from outcome expectancy). The second meaning reflects motivation based on---in his examples---anticipated "disgust, embarrassment, guilt, or shame". The second would be a motivation measurement, not a self-efficacy one. The risk is to interpret *"I can do \[target behaviour\]"* as *"I will do \[target behavior\]"*.

The *can/can't do* scale approach would be useful if Self-efficacy is measured as *task self-efficacy*, this is, focusing on the isolated task, with no context o background. But we know in complex activities this becomes difficult, so it's better to opt for other strategies such as *can-do-motivation one ("I could do it if I would like to do it")*.

## References {.unnumbered}
