---
title: "Digital Divide Framework"
author: "Ismael Aguayo"
---

## Digital divide framework

In sociology, stratification has served as a significant category, sparking numerous debates and proposals aimed at addressing the complex task of hierarchically ordering individuals in society and accounting for the inequalities they experience. A notable proposal, particularly in dichotomous situations (e.g., men and women), is the concept of the gap. This concept has been utilized as an indicator of the differences between two groups, such as the STEM graduation gap between men and women. Following the technological revolution, individuals faced a variety of new capabilities and tools essential for production. This shift forced academia and public policy to conceptualize ICT related inequalities that no longer reflected merely access disparities but also reinforced preexisting inequalities (e.g., income inequality).

The concept of the digital divide, as outlined by @lythreatis_digital_2022, refers to the various gaps in access, usage, and outcomes associated with Information and Communication Technologies (ICT). This concept, coined by scholars during the 1990s, has gained increasing prominence due to the rise of the digital economy. It has been embraced by numerous organizations and public policy institutions. For instance, the United Nations places significant emphasis on ICT as a means to achieve its Sustainable Development Goals (SDGs) and combat social inequalities. The significance of the concept lies not only in its impact on individuals' relationships with the digital world but also in its implications for social mobility, given the pervasive integration of ICT into both the labor market and educational systems. Scholars have proposed three levels or dimensions of the digital divide, each characterized by specific features and contexts.

This section summarizes a review of the literature on the digital divide coducted by @lythreatis_digital_2022. Their contributions provide a conceptual framework and bibliography to understand digital inequalities, which are addressed throughout this agenda. Further expansion of this chapter could include a more extensive historical overview of the concept and its evolution, as well as a discussion of criticisms and alternative approaches.

As mentioned earlier, three degrees of the digital divide have been proposed. The first to emerge is the most restrictive, focusing solely on disparities in ICT access within the population. This was conceptualized simply as a dichotomy between those with effective access to technology and those without.

At the dawn of the new millennium, scholars recognized the need to broaden the concept, as access disparities alone failed to capture the growing inequalities tied to technology and digitalization. The second level of the digital divide encompasses differences in access to relevant content, the quality of connectivity, digital knowledge and skills, and attitudes, behaviors, and emotions toward technology.

A third level of the digital divide emerged as a critique of the assumption that equal access and use of ICT would necessarily yield equal outcomes. This dimension emphasizes the need to examine the benefits or consequences derived from ICT usage.

The concept of the digital divide has been studied through various approaches and a wide range of variables, leading to its characterization as a multidimensional and dynamic phenomenon. This framework reflects the rapid pace of technological change in contemporary society. Key determinants of the digital divide include age, gender, socioeconomic status, attitudes, beliefs, emotions, ICT experience and training, rights, infrastructure, and large-scale events such as COVID-19.

Recent literature has proposed additional levels of the digital divide. Bartikowski et al. [2018, as cited in @lythreatis_digital_2022] argued that the type of internet use is a critical component of the divide. Cinamon \[2020, as cited in @lythreatis_digital_2022\] highlighted data inequalities as a significant but underexplored aspect. Gran et al. \[2021, as cited in @lythreatis_digital_2022\] introduced a fourth level of the divide, which examines the positive and negative effects of algorithms on individuals. Awareness of and access to information about algorithms is emerging as a crucial societal issue, particularly as algorithms play an increasing role in public participation, posing challenges to democracy.

Integrating this research agenda into the broader literature on the digital divide is essential. Self-efficacy, a psychological construct related to individuals’ belief in their ability to perform tasks, aligns with the second level of the digital divide but also acts as a predictor of digital skills and outcomes achieved through digital technologies. Additonally, the Digital Self-Efficacy (DSE) research agenda of NUDOS social team aims to explore potential gender differences and their relationship with countries' levels of development—topics that closely align with studies on the digital divide. Self-efficacy is strongly connected to learning (and therefore literacy and skills), particularly in today’s context of rapid technological change, which necessitates constant skill acquisition. Technology-related self-efficacy is also linked to Internet use and adoption, providing an alternative explanation for the digital divide beyond traditional socioeconomic factors [@eastin_internet_2000]. High self-efficacy enables individuals to adapt to the dynamic labor and educational environments and to independently acquire the knowledge required by current circumstances.

## References
