---
title: "Digital Self-efficacy Divide"
author: "Ismael Aguayo"
---

## First Self-efficacy divide: access

Access is positioned as a crucial variable for Digital Self-Efficacy (DSE), as it represents the first element of the digital divide problematized in academic studies. Recent literature highlights a positive relationship between greater access to technology and higher levels of DSE. Stone (2020) identifies a significant relationship between increased access to ICT and greater self-efficacy in the domains of basic computing, internet use, applications, and content creation. Previous studies have also documented this relationship (Tondeur, Sinnaee, Van Houtte, & Van Braak, 2011, as cited in @hatlevik_students_2018a; Aesaert & Van Braak, 2014; Tsai & Tsai, 2010; Zhong, 2011, as cited in @senkbeil_how_2023).

Due to the simplicity of the dichotomy between access and lack of access to technology, multiple dimensions of access disparities to ICT have been proposed. A study by @ball_call_2020 examines how these various dimensions relate to DSE, dividing it into Technology Self-Efficacy (TSE) and Application Self-Efficacy (ASE). Among the key findings, a significant relationship was observed between access to and use of computers at home and TSE; however, no such relationship was found with ASE.

## The socio-economic divide

The relationship between DSE and socioeconomic variables has also garnered academic interest, focusing on the connection between technological self-efficacies and factors such as cultural capital, parental education, and income. @hatlevik_students_2018a found that ICT self-efficacy significantly increases with higher socioeconomic status in 11 countries. Similarly, @chen_ictrelated_2020, using PISA 2015 data, identified a significant relationship between socioeconomic level and ICT self-efficacy, although the effect was not very strong (varying across countries between 0.0241 and 0.1678). Additionally, @chikezie_measuring_2024 reported that socioeconomic status is a significant predictor of technological self-efficacy. In contrast, @stone_ict_2020 did not find a significant relationship between parental income (as reported by university students) and technology-related self-efficacy. Lastly, @bonanati_digital_2022a demonstrated a relationship between parental social capital and technological self-efficacy.

In summary, although there is a relationship between socioeconomic status and self-efficacy, this effect ranges from low to moderate and is not consistent across all countries. For this reason, it seems important to delve deeper into this relationship, considering various factors that determine household socioeconomic status. This is particularly relevant given that socioeconomic status consistently has the most significant effect on CIL across 14 countries (@hatlevik_students_2018a).

## The gender divide

Gender has been a significant variable in studies on Digital Self-Efficacy (DSE). It is considered important due to the historical gender digital divide across all three levels and because DSE serves as an essential predictor of Computer and Information Literacy (CIL) (@hatlevik_students_2018a). Moreover, DSE partially mediates gender differences in CIL and Computational Thinking (@campos_digital_2024). Historically, a gender gap favoring males has been observed, with men displaying higher DSE and more positive attitudes toward technology (Whitley, 1997, as cited in @cai_gender_2017a). However, more recent studies highlight inconsistencies in the direction of this relationship (@cai_gender_2017a). For instance, one study finds that men demonstrate higher technological self-efficacy (Yau and Cheng, 2012, as cited in @cai_gender_2017a; Fraillon, 2014), another reports no significant differences (Compton, Burkett, and Burkett, 2003, as cited in @cai_gender_2017a), and some even indicate a reversed relationship (Compton et al., 2003, as cited in @cai_gender_2017a; Ray et al., 1999, as cited in @cai_gender_2017a). As a result, numerous studies continue to scrutinize the relationship between various types of technological self-efficacy (ICT self-efficacy, internet self-efficacy, DSE, etc.) and gender.

A meta-analysis by @cai_gender_2017a highlights that men exhibit better attitudes toward technology, including self-efficacy. Notably, the technological self-efficacy gap between men and women is the most reduced across years among those examined in the study. Additionally, @scherer_revisiting_2015, using teacher questionnaire data from ICILS 2013, identify a relationship between being male and having higher computational self-efficacy. Contrary to these findings, a study by @hatlevik_students_2018a using ICILS 2013 data reveals that women exhibit higher ICT self-efficacy, with effects ranging from 0.04 to 0.15 across nine sampled countries. Consistent with Hatlevik's findings, Chen and Hu (2020), using PISA 2015 data, report a negative effect of being male on ICT self-efficacy, varying between -0.4369 and -0.1236 depending on the country.

Given the inconsistent results from studies on the relationship between gender and DSE, the construct has been segmented to better understand this complex relationship. As previously mentioned, two dimensions of DSE have been proposed: a basic dimension addressing tasks such as internet searches, communication, and social media use, and a specialized dimension involving more complex skills like programming or server management. @gebhardt_student_2019 and Castillo et al. (2025) (a study conducted solely in Chile) argue, using ICILS 2018 data, that women have higher basic DSE, while men score higher on average in specialized DSE.

Departing from studies that rely on Large Assessment Study data (which, according to this review, are predominant), @stone_ict_2020 developed a questionnaire comprising various batteries to measure different dimensions of technology-related self-efficacy. Administered to university applicants in the United States (n=260), the study found that women scored higher in the social media dimension (5.0 vs. 4.0, p\<0.01), while men scored higher in the basic computing dimension (3.79 vs. 3.48, p\<0.05). 

## Second divide variables

The second level of the digital divide encompasses attitudes, skills, behaviors, and technology-related uses, which recent literature highlights as significant predictors of DSE. Multiple studies have explored the relationship between specific types of ICT use, attitudes toward ICT, ICT-related learning environments, and technological self-efficacy. For instance, a study by @chen_ictrelated_2020 confirms that interest is positively and significantly related to DSE. Additionally, it finds that ICT use for leisure and socialization are important mediators of this effect, whereas ICT use at school or for school-related tasks is not. This finding is supported by numerous studies; for example, @ball_call_2020 demonstrates that using ICT to talk with friends or play video games significantly affects technological self-efficacy. Similarly, @hori_impact_2021 show that ICT use in schools does not impact self-efficacy, whereas ICT use at home for learning and leisure significantly does.

The above suggests that the development of high technological self-efficacy in an individual occurs primarily in the home environment, particularly influenced by the context of learning, use, and types of technology usage. @bonanati_digital_2022a explore the relationship between characteristics of the home learning environment and ICT self-efficacy. The authors reveal that children whose parents engage in more online activities with them tend to have higher self-efficacy and identify a relationship between parental attitudes and their children's self-efficacy. In line with this, @hammer_new_2021 demonstrate that parental values and beliefs are related to children's digital self-efficacy; however, this relationship is mediated only by the age at which children are given smartphones. Relatedly, @lai_classes_2022 argue that greater smartphone use is positively associated with DSE, though problematic uses and cases where the relationship is reversed also exist.

@hatlevik_students_2018a finds that autonomous learning is positively related to ICT self-efficacy, making it the most consistently observed relationship across countries. @eastin_internet_2000 discover that outcome expectations are also linked to DSE, as is internet use experience, which is identified as the best predictor in their study.

## School and country level

Studies addressing digital self-efficacy (DSE) typically involve different nested levels, as they are mostly conducted using data from International Large-Scale Assessments (ILSA). However, the school level is often not a significant variable. For example, @chen_ictrelated_2020 conducted a multilevel model including schools across 30 countries, finding that the intraclass correlation (ICC) was less than 0.05 in all countries, with the sole exception of Mexico. Similarly, @juhanak_relationship_2019 found that the ICC was below 0.05 in all countries in their sample (using PISA 2015 data from 21 countries), concluding that only 0.09% of perceived ICT competence could be explained by school characteristics. These results are replicated in ICILS 2013, where @hatlevik_students_2018a found that the variation explained by schools was less than 6% in all countries, with Turkey being the only exception. An ICC below 0.05 is commonly conceptualized as small in the context of educational studies. A previous study corroborates these findings, dating back to PISA 2003 (ICC = 0.044) and PISA 2006 (ICC = 0.05, barely reaching the threshold) [@zhong_access_2011].

Possible explanations for this emerge from the literature review, suggesting that ICT use in schools, as opposed to ICT use for leisure or socialization, is not a relevant variable for explaining DSE [@chen_ictrelated_2020; @hori_impact_2021; @ball_call_2020]. Additionally, one article finds that the use of ICT at home for school-related tasks is a less significant mediator than other ICT-related variables [@juhanak_relationship_2019]. A potential hypothesis (arising purely from the author's intuition) is that digital self-efficacy is reinforced by motivation, which, in the context of technology, might develop more robustly in leisure activities or communication-based activities, such as social media or video games. School activities, and increased ICT adoption in these, might discourage students from developing their digital skills as they associate them with an unavoidable responsibility.

At the country level, for similar reasons as at the school level, it is sometimes included in the analysis. Whether as an additional hierarchical level in the model or through models applied individually to each country, several studies have identified heterogeneity in self-efficacy across countries, as well as in the effect sizes of the independent variables employed. For instance, @zhong_access_2011 found a higher correlation between classes at the country level than at the school level, with values of 0.077 in PISA 2003 and 0.079 in PISA 2006. However, the inclusion of the country level is usually aimed only at visualizing the heterogeneity or homogeneity of an effect, without specifically focusing on the relationship between country-level dependent variables and self-efficacy or even their effects. This is the case with studies such as those by @hatlevik_students_2018a and @chen_ictrelated_2020, for example.

However, future research needs to identify explanations for these differences, which intuitively could stem from various reasons. For instance, the degree of connectivity and technological infrastructure achieved in a country might be a significant factor influencing technology-related self-efficacy, as the population would have different levels of exposure to and familiarity with ICT. Thus, exploring various explanations for this heterogeneity is essential, as it is crucial to address digital inequalities between countries with differing levels of technological development.

## References {.unnumbered}
